Fixed compiler warnings in main Fixed formatting Added int2bin to def.h Some minor other changes

diff --git a/def b/def
--- a/def
+++ b/def
@@ -2,6 +2,7 @@
 # shellcheck disable=2034
 # shellcheck disable=2317
 # shellcheck disable=1090
+# shellcheck disable=2329
 #---------------------------------------------------------------------
 #
 #  def
@@ -220,16 +221,16 @@ bpInitSettings() {
   BP_VERSION="1.00"
 
   ##V Usage info
-  BP_USAGE="Usage: ${BP_SELF} command [option]"
+  BP_USAGE="Usage: ${BP_SELF_NAME} command [option]"
 
   ##V Description text
-  BP_DESC="Description goes here"
+  BP_DESC=""
 
   ##V logfile (uncomment to use logfile)
-  #BP_LOGFILE=${BP_SELF_DIR}/${BP_SELF}.log
+  BP_LOGFILE=${BP_SELF_DIR}/${BP_SELF_NAME}.log
 
   ##V Lock file (uncomment to use lock file feature )
-  #BP_LOCK_FILE=/tmp/${BP_SELF}.lock
+  #BP_LOCK_FILE=/tmp/${BP_SELF_NAME}.lock
 
   ##V Logging options (uncomment to activate logging parameters)
   BP_LOG_OK=1
@@ -281,6 +282,7 @@ signalInt() {
 
 signalHup() {
   bpCleanUp
+  exit "$BP_OK"
 }
 
 signalQuit() {
@@ -319,8 +321,8 @@ bpCallStack() { ##I Print out BASH call stack
   bpPrintLine
 }
 
-bpCleanUp() {           ##I Cleanup function
-  rm -f "$BP_LOCK_FILE" # remove Lock file
+bpCleanUp() {             ##I Cleanup function
+  rm -f "${BP_LOCK_FILE}" # remove Lock file
   #  echo -e "${E_SHOW}"     # Turn on cursor if turned of
 }
 
@@ -337,7 +339,7 @@ bpExit() { ##I Function for safely exiting script
 
   # Check if argument is given
   if [ -z "$1" ]; then
-    exit 0 # Success
+    exit "$BP_OK"
   else
     exit "$1"
   fi
@@ -413,6 +415,7 @@ E_UL_BR_CYAN=$'\e[58;5;14m'    # Bright Cyan
 E_UL_WHITE=$'\e[58;5;15m'      # White
 
 # ANSI Text attributes
+E_RESET=$'\e[0m'              # Clear all attributes
 E_BOLD=$'\e[1m'               # Bold text
 E_DIM=$'\e[2m'                # Dim(low intensity) text
 E_ITALIC=$'\e[3m'             # Italic text
@@ -441,8 +444,6 @@ E_BACK=$'\e[D'    # Move cursor backward
 E_HIDE=$'\e[?25l' # Hide cursor
 E_SHOW=$'\e[?25h' # Show cursor
 
-E_RESET=$'\e[0m' # Clear Attributes
-
 # Default Bashplate colortheme
 BP_C_OK="${E_BR_GREEN}"
 BP_C_INFO="${E_BR_CYAN}"
@@ -463,11 +464,19 @@ BP_C_URL_SCHEME="${E_DARKGRAY}"
 BP_C_TIME="${E_BR_MAGENTA}"
 BP_C_DATE="${E_MAGENTA}"
 
+BP_C_QUERY=$'\e[38;5;194m'
+BP_C_QUERY_DEF=$'\e[38;5;240m'
+BP_C_EMPHASIS=$'\e[38;5;255m'
+BP_C_DEEMPHASIS=$'\e[38;5;250m'
+
 # Shellscript colorize colors
 BP_C_RESERVED="${E_RED}"
 BP_C_COMMENT="${E_CYAN}"
 BP_C_STRING="${E_GREEN}"
 BP_C_VAR="${E_BR_YELLOW}"
+
+# Separator line character
+BP_LINE_CHAR="-"
 
 # Exit codes
 #
@@ -482,6 +491,7 @@ BP_RIGHT_MARGIN=3
 #---------------------------------------------------------------------
 # Bashplate internal functions
 #---------------------------------------------------------------------
+# shellcheck disable=2155
 
 ##C- IHELP Printing functions
 
@@ -490,16 +500,19 @@ BP_RIGHT_MARGIN=3
 # $2 text color
 # $3 line color
 # $4 middle character
-# $5 line character
 #
 bpPrintLineGeneric() { ##I Print text with adjusted line after with selectable colors
-  len1="${#1}"
-  len4="${#4}"
+  local len1="${#1}"
+  local len4="${#4}"
 
   echo -en "${2}${1}${4}${3}"
-  l=$((BP_COLUMNS - len1 - len4))
-  seq -s"${5}" "${l}" | tr -d '[:digit:]'
-  echo -en "${E_RESET}"
+  if [ "${BP_LINE_CHAR}" != "" ]; then
+    l=$((BP_COLUMNS - len1 - len4))
+    seq -s"${BP_LINE_CHAR}" "${l}" | tr -d '[:digit:]'
+    echo -en "${E_RESET}"
+  else
+    echo -e "${E_RESET}"
+  fi
 }
 
 #
@@ -508,14 +521,14 @@ bpPrintLineGeneric() { ##I Print text with adjusted line after with selectable c
 # $3 line color
 #
 bpTextLineC() { ##I Print text with adjusted line after with selectable colors
-  bpPrintLineGeneric "$1" "$2" "$3" " " "-"
+  bpPrintLineGeneric "$1" "$2" "$3" " "
 }
 
 bpPrintLine() { ##I Print text with line
   if [ "${#1}" -eq 0 ]; then
-    bpPrintLineGeneric "" "" "${BP_C_LINE}" "" "-"
+    bpPrintLineGeneric "" "" "${BP_C_LINE}" ""
   else
-    bpPrintLineGeneric "$1" "${BP_C_LINETEXT}" "${BP_C_LINE}" " " "-"
+    bpPrintLineGeneric "$1" "${BP_C_LINETEXT}" "${BP_C_LINE}" " "
   fi
 }
 
@@ -527,10 +540,12 @@ bpPrintLine() { ##I Print text with line
 # $5 key length override (optional)
 #
 bpPrintDescGeneric() { # Generic key/description printout function
-  KEY_COLOR="$1"
-  DESC_COLOR="$2"
-  KEY="$3"
-  DESC="$4"
+  local KEY_COLOR="$1"
+  local DESC_COLOR="$2"
+  local KEY="$3"
+  local DESC="$4"
+  local KL
+
   if [ -n "$5" ]; then
     KL="$5"
   else
@@ -581,7 +596,7 @@ bpPrintDescAlt() {
 # $3 alternative value text (optional)
 #
 bpPrintVar() { ##I Print variable value and description
-  VAR="$1"
+  local VAR="$1"
 
   if [ -n "$2" ]; then
     KEY=${2}
@@ -598,7 +613,7 @@ bpPrintVar() { ##I Print variable value and description
 
     bpPrintDesc "${KEY}" "${VAL}"
   else
-    bpPrintDescGeneric "${BP_C_KEY}" "${BP_C_ERROR}" "$KEY" "N/A"
+    bpPrintDesc "${KEY}" "${BP_C_ERROR}N/A"
   fi
 }
 
@@ -619,8 +634,8 @@ bpColorizeFile() { ##I Colorize string containing filename
 # todo: give username and port own color
 #
 bpColorizeUrl() { ##I Colorize string containing URL
-  URL=$(sed -r -e "s/^.*\/\///" <<<"$1")
-  SCHEME=$(sed -r -e "s/:\/.*//" <<<"$1")
+  local URL=$(sed -r -e "s/^.*\/\///" <<<"$1")
+  local SCHEME=$(sed -r -e "s/:\/.*//" <<<"$1")
   # USERNAME=$(sed -r -e "s/@.*//" <<<"$URL")
   # PORT=$(sed -r -e "s/^:[0-9]*/XXX/" <<<"$URL")
   # echo -e "Username: $USERNAME"
@@ -831,8 +846,8 @@ bpImport() { ## Import file into variable
 # $3 text to insert
 #
 bpInsert() { ##I Insert text into file
-  a=$(grep -A 10000 "$2" <"$1" | grep -v "$2")
-  b=$(grep -B 10000 "$2" <"$1" | grep -v "$2")
+  local a=$(grep -A 10000 "$2" <"$1" | grep -v "$2")
+  local b=$(grep -B 10000 "$2" <"$1" | grep -v "$2")
 
   echo "$b" "$3" "$a" >|"$1"
 }
@@ -844,18 +859,29 @@ bpInsert() { ##I Insert text into file
 # $2  Default value
 # return string read from cmdline/default if enter pressed
 #
-bpReadStr() { ##I Read string from commandline
+bpReadGeneric() { ##I Read from commandline
+  local QUERY="$1"
+  local DEFAULT="$2"
 
-  if [ "${2}" == "" ]; then
-    read -erp "${1} > " result
-  else
-    read -erp "${1} [$2] > " result
-    if [ "${result}" == "" ]; then
-      result="${2}"
-    fi
+  read -er -i "$DEFAULT" -p "${BP_C_QUERY}${1}${E_RESET} > " RESULT
+  if [ "${RESULT}" == "" ]; then
+    RESULT="${2}"
   fi
+  echo "${RESULT}"
+}
 
-  echo "${result}"
+#
+# $1  Question string
+# $2  Default value
+# return string read from cmdline/default if enter pressed
+#
+bpReadStr() { ##I Read string from commandline
+  QUERY="$1"
+  DEFAULT="$2"
+
+  RESULT=$(bpReadGeneric "$QUERY" "$DEFAULT")
+  bpLogInfo "User entered: $RESULT  ($QUERY)"
+  echo "${RESULT}"
 }
 
 #
@@ -866,23 +892,33 @@ bpReadStr() { ##I Read string from commandline
 # return integer read from cmdline/default if enter pressed
 #
 bpReadInt() { ##I Read integer from commandline
+  local QUERY="$1"
+  local DEFAULT="$2"
+  local MIN="$3"
+  local MAX="$4"
+  local RANGE=""
+
+  if [ -n "$MIN" ] || [ -n "$MAX" ]; then
+    RANGE=" ${BP_C_QUERY_DEF}[${E_RESET}$3-$4${BP_C_QUERY_DEF}]${E_RESET}"
+  fi
+
   while true; do
-    if [ "${2}" == "" ]; then
-      read -erp "${1} ($3-$4) >" result
-      if [ "${result}" == "" ]; then
-        result=$(($3 - 1))
+    read -er -i "$DEFAULT" -p "${BP_C_QUERY}${1}${E_RESET}${RANGE} > " RESULT
+
+    if [ "$RESULT" -eq "$RESULT" ] 2>/dev/null; then
+
+      if [ -n "${RANGE}" ]; then
+        #if [ -n "$MIN" ] && [ -n "$MAX" ]; then
+        if [ $((RESULT)) -ge "$MIN" ] && [ $((RESULT)) -le "$MAX" ]; then
+          break
+        fi
+      else
+        break
       fi
-    else
-      read -erp "${1} ($3-$4) [$2] >" result
-      if [ "${result}" == "" ]; then
-        result="${2}"
-      fi
-    fi
-    if [ $((result)) -ge "$3" ] && [ $((result)) -le "$4" ]; then
-      break
     fi
   done
-  echo "${result}"
+  bpLogInfo "User entered: $RESULT  ($QUERY)"
+  echo "${RESULT}"
 }
 
 #
@@ -891,24 +927,33 @@ bpReadInt() { ##I Read integer from commandline
 # return 0 = Yes, 1=No
 #
 bpReadBool() { ##I Ask yes/no question generic
+  local QUERY="$1"
+  local DEFAULT="$2"
   while true; do
 
     if [ "$2" -eq 1 ]; then
-      yn=$(bpReadStr "${1} [y/N]")
+      yn=$(bpReadGeneric "${BP_C_QUERY}${1}${E_RESET} ${BP_C_QUERY_DEF}[${BP_C_DEEMPHASIS}y${BP_C_QUERY_DEF}/${BP_C_EMPHASIS}N${BP_C_QUERY_DEF}]${E_RESET}")
     else
-      yn=$(bpReadStr "${1} [Y/n]")
+      yn=$(bpReadGeneric "${BP_C_QUERY}${1}${E_RESET} ${BP_C_QUERY_DEF}[${E_RESET}${BP_C_EMPHASIS}Y${BP_C_QUERY_DEF}/${BP_C_DEEMPHASIS}n${BP_C_QUERY_DEF}]${E_RESET}")
     fi
 
     case "$yn" in
     [Yy]*)
+      bpLogInfo "User entered: Yes  ($QUERY)"
       return 0
       break
       ;;
     [Nn]*)
+      bpLogInfo "User entered: No  ($QUERY)"
       return 1
       break
       ;;
     "")
+      if [ "$2" -eq 0 ]; then
+        bpLogInfo "User entered: Yes  ($QUERY)"
+      else
+        bpLogInfo "User entered: No  ($QUERY)"
+      fi
       return "$2"
       break
       ;;
@@ -937,9 +982,9 @@ bpReadBoolDN() { ##I Ask yes/no question default no
 
 bpPrintChoiceList() { # Print items in selection list
   echo
-  arr=("${@:2}")
-  len=${#arr[@]}
-  i=1
+  local arr=("${@:2}")
+  local len=${#arr[@]}
+  local i=1
   while [ "$i" -lt "$len" ]; do
     key=${arr[$i]}
     ((i++))
@@ -978,14 +1023,15 @@ bpPrintChoiceList() { # Print items in selection list
 #  "c" ":" "Choice C"
 # )
 bpSelectFromList() { ##I Select from list
-
+  local QUERY="$2"
   while true; do
     bpPrintChoiceList "$1" "${@:2}"
-    x=$(bpReadStr "$2" "$1")
+    echo
+    local x=$(bpReadGeneric "$2" "$1")
 
-    arr=("${@}")
-    len=${#arr[@]}
-    i=2
+    local arr=("${@}")
+    local len=${#arr[@]}
+    local i=2
     while [ "$i" -lt "$len" ]; do
       key=${arr[$i]}
       ((i++))
@@ -998,6 +1044,7 @@ bpSelectFromList() { ##I Select from list
         else
           bpReturn="${val}"
         fi
+        bpLogInfo "User entered: $bpReturn  ($QUERY)"
         return 0
       fi
     done
@@ -1042,7 +1089,7 @@ bpChangeSetting() { ##I Change setting in config file
   if ! bpStrExist "${1}" "${KEY}"; then
     bpAddSetting "$FILE" "$KEY" "$VAL" "$DESC"
   fi
-  sed -i "s/^\(${KEY}\s*=\s*\).*\$/\1\"${VAL}\"/" "${FILE}"
+  sed -i "s/^\(${KEY}\s*=\s*\).*\$/\1${VAL}/" "${FILE}"
   bpOk "Changing ${KEY} to ${VAL}"
 }
 
@@ -1051,10 +1098,10 @@ bpChangeSetting() { ##I Change setting in config file
 # $2 config array
 #
 bpConfGetDesc() { ##I Get config desription
-  arr=("${@:1}")
-  len=${#arr[@]}
+  local arr=("${@:1}")
+  local len=${#arr[@]}
   bpReturn=""
-  i=1
+  local i=1
   while [ "$i" -lt "$len" ]; do
     key=${arr[$i]}
     ((i++))
@@ -1077,11 +1124,11 @@ bpConfGetDesc() { ##I Get config desription
 # $3 config array
 #
 bpConfChangeSetting() {
-  KEY="$1"
-  VAL="$2"
-  CONF=("${@:2}")
-  FILE=${CONF[1]}
-  DESC=$(bpConfGetDesc "$KEY" "${CONF[@]}")
+  local KEY="$1"
+  local VAL="$2"
+  local CONF=("${@:2}")
+  local FILE=${CONF[1]}
+  local DESC=$(bpConfGetDesc "$KEY" "${CONF[@]}")
 
   if ! bpConfInList "$KEY" "${CONF[@]}"; then
     bpError "\"$KEY\" is not a valid setting"
@@ -1102,7 +1149,7 @@ bpConfChangeSetting() {
 # $3 config array
 #
 bpConfCreate() { ##I Create configuration file
-  FILE="$1"
+  local FILE="$1"
   {
     echo "# "
     echo "# $2"
@@ -1110,9 +1157,9 @@ bpConfCreate() { ##I Create configuration file
     echo
   } >>"${FILE}"
 
-  arr=("${@:2}")
-  len=${#arr[@]}
-  i=1
+  local arr=("${@:2}")
+  local len=${#arr[@]}
+  local i=1
   while [ "$i" -lt "$len" ]; do
     key=${arr[$i]}
     ((i++))
@@ -1141,10 +1188,10 @@ bpConfLoad() { ##I Load config file
 # $2 config array
 #
 bpConfInList() { ##I Check if key exist in config file list
-  arr=("${@:1}")
-  len=${#arr[@]}
+  local arr=("${@:1}")
+  local len=${#arr[@]}
   bpReturn=""
-  i=1
+  local i=3
   while [ "$i" -lt "$len" ]; do
     key=${arr[$i]}
     ((i++))
@@ -1152,8 +1199,9 @@ bpConfInList() { ##I Check if key exist in config file list
     ((i++))
     desc=${arr[$i]}
     ((i++))
-    #echo "$key"
+    #echo "Key = $key  Default = $def  Desc = $desc"
     if [ "$key" == "$1" ]; then
+      bpReturn="$key"
       return 0
     fi
   done
@@ -1164,8 +1212,8 @@ bpConfPrint() { ##I Print settings in config list
   echo
   bpPrintDesc "Config file" "$(bpColorizeFile "$3")"
   echo
-  arr=("${@:4}")
-  i=1
+  local arr=("${@:4}")
+  local i=1
   while [ "$i" -lt ${#arr[@]} ]; do
     KEY=${arr[$i]}
     ((i++))
@@ -1174,7 +1222,7 @@ bpConfPrint() { ##I Print settings in config list
     DESC=${arr[$i]}
     ((i++))
     printf "%s%s\n" "${E_DARKGRAY}" "${DESC}"
-    bpPrintVar "$KEY" #"${!KEY}"
+    bpPrintVar "$KEY"
   done
 }
 
@@ -1395,7 +1443,7 @@ bpAssertProgs() { ##I Assert that required programs are available on the system
         e=1
       }
   done
-  if [ $e -eq 1 ]; then
+  if [ "$e" -eq 1 ]; then
     bpExit 1
   fi
 }
@@ -1405,7 +1453,7 @@ bpAssertProgs() { ##I Assert that required programs are available on the system
 #
 # $1 command to check
 #
-bpHasCmd() { ##I Check if command is available
+bpHasCmd() { ##I Check whether a command exists in path and is executable
   if [ -x "$(command -v "${1}")" ]; then
     return 0
   else
@@ -1434,13 +1482,27 @@ bpGetFunction() {
 # $1 command to execute
 #
 bpRun() { ##I Execute command
-  if bpHasCmd "${1}"; then
-    "$@"
-    return $?
-  else
+  if ! bpHasCmd "${1}"; then
     bpError "Could not execute $1, command does not exist!"
     return 1
   fi
+
+  "$@"
+  return $?
+}
+
+#
+# $1 name of hook to execute
+#
+bpExecHook() {
+  local HOOK=${!1}
+
+  # execute hook if existing
+  if bpIsFunction "${HOOK}"; then
+    ${HOOK} "$@"
+    return 0
+  fi
+  return 1
 }
 
 ##C- IHELP Debug/Controll
@@ -1459,15 +1521,15 @@ irt() { ##I Remove tabs from script
 printCommand() {
   IFS=$' '
   read -r -a LINE <<<"$1"
-  DESC="${LINE[*]:3}"
+  local DESC="${LINE[*]:3}"
   bpPrintDesc "${LINE[0]}" "${DESC}"
 }
 
 printCondCommand() {
   IFS=$' '
   read -r -a LINE <<<"$1"
-  DESC="${LINE[*]:4}"
-  COND=${LINE[3]}
+  local DESC="${LINE[*]:4}"
+  local COND=${LINE[3]}
 
   if [ -n "$IHELP" ] && [ "$COND" != "IHELP" ]; then
     return
@@ -1493,8 +1555,8 @@ printNamedLine() {
 printCondNamedLine() {
   IFS=$' '
   read -r -a LINE <<<"$1"
-  DESC=${LINE[*]:2}
-  COND=${LINE[1]}
+  local DESC=${LINE[*]:2}
+  local COND=${LINE[1]}
 
   if [ -n "$IHELP" ] && [ "$COND" != "IHELP" ]; then
     return
@@ -1516,13 +1578,10 @@ help() { ##D Print help information
     BPINIT=1
   fi
 
-  # bpExecHook "PRE_HELP_HOOK"
-  if [ -n "$PRE_HELP_HOOK" ]; then
-    "${PRE_HELP_HOOK}"
-  fi
+  bpExecHook "PRE_HELP_HOOK"
 
   IFS=$'\n'
-  SC="$1"
+  local LINES
   LINES=$(grep -h '##' "$0" | grep -v -e 'grep' -e '##I' -e '##V' -e '\*##C' -e '\*##C-' -e '\"##' -e '##-//' -e 'LINE' -e 'printLine')
   LINES="${LINES//()/}"
 
@@ -1538,9 +1597,7 @@ help() { ##D Print help information
     esac
   done
 
-  if [ -n "$POST_HELP_HOOK" ]; then
-    "${POST_HELP_HOOK}"
-  fi
+  bpExecHook "POST_HELP_HOOK"
 }
 
 #
@@ -1562,11 +1619,10 @@ ihelp() { ##I Print internal help information
   fi
 
   IFS=$'\n'
-  SC="$1"
-
   IHELP=1      # Force ihelp documentations
   BP_LOGFILE=1 # Force log documentation
 
+  local LINES
   LINES=$(grep -h '##[C|I]' "$0" | grep -v -e 'grep' -e '\*"##[ A-Z]"\*' -e 'LINE' -e 'printNamedLine' -e 'awk' -e 'bpPrintDesc' -e 'name')
   LINES=$(echo -e "$LINES" | sed -s 's/()//g')
 
@@ -1593,7 +1649,7 @@ iinfo() { ##I Show information about script
   bpPrintLine "Script information"
   bpPrintVar BP_SELF "Script" "$(bpColorizeFile "${BP_SELF_DIR}/${BP_SELF}")"
   bpPrintVar BP_VERSION "Script version"
-  bpPrintVar BP_VERSION "Template version"
+  bpPrintVar BP_TEMPLATE_VERSION "Template version"
   bpPrintVar BP_CONFIG "Bashplate settings file" "$(bpColorizeFile "${BP_CONFIG}")"
   bpPrintVar BP_LOGFILE "Log file" "$(bpColorizeFile "${BP_LOGFILE}")"
   bpPrintVar BP_LOCK_FILE "Lock file" "$(bpColorizeFile "${BP_LOCK_FILE}")"
@@ -1601,12 +1657,13 @@ iinfo() { ##I Show information about script
   bpPrintDesc "PID" $$
   bpPrintVar BP_DATE "Date"
   bpPrintVar BP_TIME "Time"
+  bpPrintVar TERM "Terminal"
   bpPrintVar BP_COLUMNS "Terminal columns"
   bpPrintVar BP_LINES "Terminal lines"
 
   if [ -n "${POST_INFO_HOOK}" ]; then
     bpPrintLine "App. information"
-    ${POST_INFO_HOOK}
+    bpExecHook "POST_INFO_HOOK"
   fi
 
   if [ -z "$BP_CONF" ]; then
@@ -1614,13 +1671,13 @@ iinfo() { ##I Show information about script
     return
   fi
   bpPrintLine "Bashplate config"
-  i=2
+  local i=2
   while [ "$i" -lt ${#BP_CONFIG_LIST[@]} ]; do
     KEY=${BP_CONFIG_LIST[$i]}
     ((i++))
     ((i++))
     ((i++))
-    bpPrintVar "$KEY" "$KEY"
+    bpPrintVar "$KEY"
   done
 
   bpPrintLine
@@ -1712,7 +1769,7 @@ bpRunCommand() {
   fi
 
   # Check if command is conditional
-  CL=$(grep -E "${command}().*##C" "$0")
+  CL=$(grep -E "${command}\(\).*##C" "$0")
   if [[ "$CL" = *"##C"* ]]; then
 
     # Check if condition is true and then execute else printout error message
@@ -1734,9 +1791,8 @@ bpRunCommand() {
   fi
 
   # execute post command hook  if existing
-  if [ -n "$POST_CMD_HOOK" ]; then
-    "${POST_CMD_HOOK}" "$command"
-  fi
+  bpExecHook "POST_CMD_HOOK"
+
   bpExit
 }
 
@@ -1745,12 +1801,15 @@ bpRunCommand() {
 #---------------------------------------------------------------------
 
 ##V Bashplate version
-BP_VERSION="1.20"
+BP_TEMPLATE_VERSION="1.40beta2"
 
 ##V Directory where script is located
 BP_SELF_DIR="${0%/*}"
 
 ##V Name of script
+BP_SELF_NAME=$(basename "$0")
+
+##V Name of script (to be repurposed)
 BP_SELF=$(basename "$0")
 
 ##V Number of arguments given to script
@@ -1808,9 +1867,13 @@ BP_CONFIG_LIST=(
   "BP_NAME" "John Doe" "Users name"
   "BP_EMAIL" "john.doe@foo.bar" "Users email"
   "BP_ORG" "ACME" "Organisation"
+  "BP_HOME" "www.foo.bar" "Home"
   "BP_LICENSE" "MIT" "Default license"
   "BP_EDITOR" "vi" "Default editor"
   "BP_DIFF" "meld" "Default diff program"
+  "BP_GITSERVER" "github.com" "Default git server"
+  "BP_GITUSER" "" "Default git user"
+  "BP_GITPROTO" "http" "Default git protocol"
 )
 
 # Load configuration file settings
